### ISSUE TITLE
Document the --workspace command line switch

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#1169] opened 2020-09-16 07:51 UTC
We have a --workspace switch for `tkn * start` command which accept some obscure
argument like :

```
--workspace name=<workspace-name>,claimName=<pvc-name>
```

or

```
--workspace name=<workspace-name>,volumeClaimTemplateFile=<path-to-template>
```

but nothing is documented in the `--help` switch

/kind feature
/kind documentation

**Comment by danielhelfand** [comment] 2020-09-17 12:48
Dupe of https://github.com/tektoncd/cli/issues/895. I'll close it in favor of this, but agree that better examples/descriptions should be provided.

**Comment by afrittoli** [comment] 2021-02-13 12:37
I guess until this is solved, it would be good to have a few more examples pasted here.
There are a few in https://github.com/tektoncd/cli/blob/master/docs/cmd/tkn_pipeline_start.md, but there's no example for the template case.

**Closed** 2021-06-02 18:37 UTC
Labels: kind/documentation, kind/feature, lifecycle/frozen
