### ISSUE TITLE
Unable to use multiple doc YAML with tkn create commands

### ISSUE THREAD

**Issue by kameshsampath** [tektoncd/cli#602] opened 2020-01-14 17:32 UTC
/kind feature

# Version and Operating System
macOS Catalina

**tkn Version:** `Client version: v0.6.0`

**Operating System:**  macOS

# Expected Behavior

The tkn create commands for `tkn task create` or `tkn res create` should accept Tekton resource YAML with multiple documents. 

# Actual Behavior

Right now only the first document is parsed and processed.

# Steps to Reproduce the Problem

1. tkn res create -f https://gist.githubusercontent.com/kameshsampath/90a2031c0d3b55dc982e3789900dac4f/raw/5ead712636f5f758195158cd92aba77f0aeaf539/build-resources.yaml

**Comment by kameshsampath** [comment] 2020-01-14 17:33
CC: @hrishin , @piyush-garg

**Comment by danielhelfand** [comment] 2020-01-14 18:01
Hey @kameshsampath. Thanks for opening this.

 I believe we will actually be going with a different approach in #582 where `tkn` actually directly invokes `kubectl create` and `kubectl apply` and repurposing `tkn <resource> create` commands to focus on interactive creation and working more directly with the [catalog of tasks](https://github.com/tektoncd/catalog) for tekton.

This is also a duplicate of #575, so I am going to close this for now. Please feel free to add any comments or feedback I perhaps am missing in the issues currently opened.

**Closed by danielhelfand** 2020-01-14 18:01 UTC
Labels: kind/feature

**Comment by danielhelfand** [comment] 2020-01-14 18:02
Please also note #574 for the approach in #582.
