### ISSUE TITLE
tkn pipelinerun logs <pr> throwing seg fault error

### ISSUE THREAD

**Issue by hrishin** [tektoncd/cli#603] opened 2020-01-15 09:12 UTC
# Version and Operating System

**tkn Version:**`

```
tkn version 
Client version: 0.6.0
```

**Operating System:** 

```
Fedora 30
uname --all 
Linux glhf.localdomain 5.3.11-200.fc30.x86_64 #1 SMP Tue Nov 12 19:25:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

# Expected Behavior
It should show some logs or should some nice error message

# Actual Behavior
Giving `segfault`

```
$ tkn pipelinerun logs pipelinerun-timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10da364]

goroutine 1 [running]:
github.com/tektoncd/cli/pkg/cmd/pipelinerun.(*LogReader).readAvailableLogs(0xc00033a0c0, 0xc000127b00, 0x13, 0x0, 0x0, 0x0)
	/workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/log_reader.go:112 +0xc4
github.com/tektoncd/cli/pkg/cmd/pipelinerun.(*LogReader).Read(0xc00033a0c0, 0xc00033a0c0, 0x7, 0x0, 0x15a41e0)
	/workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/log_reader.go:63 +0x13d
github.com/tektoncd/cli/pkg/cmd/pipelinerun.Run(0xc0003b63f0, 0xc000381680, 0x0)
	/workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/logs.go:105 +0x18c
github.com/tektoncd/cli/pkg/cmd/pipelinerun.logCommand.func1(0xc0003b9600, 0xc0003cea20, 0x1, 0x1, 0x0, 0x0)
	/workspace/src/github.com/tektoncd/cli/pkg/cmd/pipelinerun/logs.go:66 +0x1bc
github.com/spf13/cobra.(*Command).execute(0xc0003b9600, 0xc0003ce9e0, 0x1, 0x1, 0xc0003b9600, 0xc0003ce9e0)
	/workspace/pkg/mod/github.com/chmouel/cobra@v0.0.0-20191021105835-a78788917390/command.go:832 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00037d340, 0xc000381680, 0xc00037d340, 0xc00004c118)
	/workspace/pkg/mod/github.com/chmouel/cobra@v0.0.0-20191021105835-a78788917390/command.go:920 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/pkg/mod/github.com/chmouel/cobra@v0.0.0-20191021105835-a78788917390/command.go:870
main.main()
	/workspace/src/github.com/tektoncd/cli/cmd/tkn/main.go:31 +0x4b
```

# Steps to Reproduce the Problem

1. tkn pipelinerun logs <pr-name>

# Additional Info

```
$ tkn pr ls
NAME                  STARTED         DURATION     STATUS   
pipelinerun-timeout   8 minutes ago   53 seconds   Failed   
```

/kind bug

**Comment by chmouel** [comment] 2020-01-15 09:20
Any chances if you can reproduce with `master` I cannot reproduce it...

**Comment by 16yuki0702** [comment] 2020-03-10 02:11
Maybe this is same cause of https://github.com/tektoncd/cli/issues/775

because it panicked at below code.
https://github.com/tektoncd/cli/blob/v0.6.0/pkg/cmd/pipelinerun/log_reader.go#L112

This is addressed by https://github.com/tektoncd/cli/pull/781

so can I close this issue ?

**Comment by vdemeester** [comment] 2020-03-10 07:58
Let's close this for now yeah. 
/close

**Closed by vdemeester** 2020-03-10 07:58 UTC
Labels: kind/bug
