### ISSUE TITLE
golangci-lint latest fail to lint

### ISSUE THREAD

**Issue by chmouel** [tektoncd/cli#1501] opened 2022-02-02 21:33 UTC
golangci-lint version:

`1.44.0`

lint output:

```
% make lint
Linting go files...
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.
pkg/bundle/keychain_test.go:91:42: badCall: suspicious Join on 1 argument (gocritic)
		assert.Equal(t, getPathToPodmanAuth(), filepath.Join("/run/user/1000/containers/auth.json"))
		                                       ^
test/e2e/eventListener/eventListener_test.go:1: File is not `gofmt`-ed with `-s` (gofmt)
// +build e2e
test/e2e/plugin/plugin_test.go:1: File is not `gofmt`-ed with `-s` (gofmt)
// +build e2e
test/e2e/pipelinerun/pipelinerun_test.go:1: File is not `gofmt`-ed with `-s` (gofmt)
// +build e2e
test/e2e/resource/create_test.go:1: File is not `gofmt`-ed with `-s` (gofmt)
// +build e2e
test/e2e/clustertask/start_test.go:1: File is not `gofmt`-ed with `-s` (gofmt)
// +build e2e
test/e2e/task/start_test.go:1: File is not `gofmt`-ed with `-s` (gofmt)
// +build e2e
test/e2e/pipeline/pipeline_test.go:1: File is not `gofmt`-ed with `-s` (gofmt)
// +build e2e
test/e2e/pipeline/start_test.go:1: File is not `gofmt`-ed with `-s` (gofmt)
// +build e2e
pkg/bundle/builder_test.go:73:3: printf: (*testing.common).Errorf does not support error-wrapping directive %w (govet)
		t.Errorf("Failed to read image layer: %w", err)
		^
pkg/bundle/builder_test.go:87:3: printf: (*testing.common).Errorf does not support error-wrapping directive %w (govet)
		t.Errorf("failed to read tar bundle: %w", err)
		^
pkg/bundle/builder_test.go:92:3: printf: (*testing.common).Errorf does not support error-wrapping directive %w (govet)
		t.Errorf("failed to decode layer contents to a Tekton object: %w", err)
		^
pkg/cmd/bundle/push_test.go:119:5: printf: (*testing.common).Errorf does not support error-wrapping directive %w (govet)
				t.Errorf("Unexpected failure calling run: %w", err)
				^
pkg/cmd/bundle/push_test.go:177:3: printf: (*testing.common).Errorf does not support error-wrapping directive %w (govet)
		t.Errorf("Failed to read image layer: %w", err)
		^
pkg/cmd/bundle/push_test.go:192:3: printf: (*testing.common).Errorf does not support error-wrapping directive %w (govet)
		t.Errorf("failed to read tar bundle: %w", err)
		^
make: *** [lint-go] Error 1
```

/assign @pradeepitm12

**Comment by pradeepitm12** [comment] 2022-02-04 07:16
Our [plumbing ](https://github.com/tektoncd/plumbing/blob/main/tekton/images/test-runner/Dockerfile#L172 ) and [cli ](https://github.com/tektoncd/cli/blob/3c9ece67610d3be38cd56847305108effad93c77/tekton/release-pipeline.yml#L57), both uses `golangci-lint v1.42.0`,
I did try https://github.com/tektoncd/cli/pull/1504 with golangci-lint v1.44.0 but we need go v1.17 or greater for it.
Should we bump go to v1.17?

**Comment by chmouel** [comment] 2022-02-04 09:21
let's keep it on 1.16 since we are "stuck" with it for rhel

**Comment by jbpratt** [comment] 2022-03-04 08:34
@chmouel @pradeepitm12 I think this is a duplicate of https://github.com/tektoncd/cli/issues/1481 which is almost resolved now! :cat:

**Comment by chmouel** [comment] 2022-03-07 07:42
@jbpratt wonderful, thank you! 🙇🏻

**Closed** 2022-03-07 07:42 UTC
Labels: kind/bug
